blank_issues_enabled: false

issue_template:
  - name: "ğŸ bug"
    description: "ë²„ê·¸ ìˆ˜ì • í…œí”Œë¦¿ì„ ì‚¬ìš©í•˜ì—¬ ë¬¸ì œë¥¼ ë³´ê³ í•˜ì„¸ìš”."
    labels: ["bug"]
    file: bug.yml

  - name: "âœï¸ fix"
    description: "ê¸°ì¡´ ê¸°ëŠ¥ ê°œì„  ë° ìˆ˜ì • "
    labels: ["fix"]
    file: fix.yml

  - name: "âœ¨ feature"
    description: "ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€ë¥¼ ì œì•ˆí•˜ê±°ë‚˜ êµ¬í˜„í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”."
    labels: ["feat"]
    file: feature.yml

  - name: "ğŸ”§ refactor"
    description: "ê¸°ëŠ¥ ë³€ê²½ ì—†ì´ ì½”ë“œ êµ¬ì¡°ë¥¼ ê°œì„ í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”. (ì˜ˆ: ì¤‘ë³µ ì œê±°, ê°€ë…ì„± í–¥ìƒ)"
    labels: ["refactor"]
    file: refactor.yml

  - name: "âš™ï¸ setting"
    description: "í”„ë¡œì íŠ¸ ì„¤ì • ë³€ê²½ (í™˜ê²½ ë³€ìˆ˜, ì˜ì¡´ì„±, Gradle íŒŒì¼ ë“±)ì„ ìš”ì²­í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”."
    labels: ["setting"]
    file: setting.yml

  - name: "ğŸ“š docs"
    description: "ë¬¸ì„œí™” ì‘ì—…ì´ í•„ìš”í•  ë•Œ ì‚¬ìš©í•˜ì„¸ìš”."
    labels: ["docs"]
    file: docs.yml

  - name: "ğŸ¨ design"
    description: "UI/UX, ì»´í¬ë„ŒíŠ¸, í™”ë©´ ë””ìì¸ ê°œì„ "
    labels: ["design"]
    file: design.yml